export const EVENT_ORGANIZER_ENDPOINT = "/api/events/organizer";
export const EVENT_PUBLIC_ENDPOINT = "/api/events";

export const EVENT_TEST_ROUTE = {
  GET_EVENTS_PUBLIC: `${EVENT_PUBLIC_ENDPOINT}`,
  GET_EVENTS_ORGANIZER: `${EVENT_ORGANIZER_ENDPOINT}`,
  GET_EVENT_ORGANIZER: (id: string) => `${EVENT_ORGANIZER_ENDPOINT}/${id}`,
  CREATE_EVENT_ORGANIZER: `${EVENT_ORGANIZER_ENDPOINT}`,
  UPDATE_EVENT_ORGANIZER: (id: string) => `${EVENT_ORGANIZER_ENDPOINT}/${id}`,
  DELETE_EVENT_ORGANIZER: (id: string) => `${EVENT_ORGANIZER_ENDPOINT}/${id}`,
}